# Generated by Django 5.0.4 on 2024-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPDFnText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200, unique=True)),
                ('pdf_file', models.FileField(upload_to='pdf/')),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('text_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RawPDF',
        ),
    ]
