# Generated by Django 5.0.4 on 2024-04-24 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rawpdfntext_text_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='pdf/')),
                ('uploaded_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RawPDFnText',
        ),
    ]
