# Generated by Django 5.0.4 on 2024-04-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rawpdf_delete_rawpdfntext'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpdf',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
