# Generated by Django 5.0.4 on 2024-04-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_extractedtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtext',
            name='text_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rawpdf',
            name='pdf_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
