# Generated by Django 5.0.4 on 2024-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_extractedtext_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtext',
            name='text_content',
            field=models.TextField(default='', null=True),
        ),
    ]
